version: "3.9"

services:
  mongo:
    image: mongo:8.2
    container_name: webapp-mongo
    restart: always
    environment:
      # Utilisateur root de Mongo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      # Base créée par défaut (même nom que dans appsettings.json: "webapp")
      - MONGO_INITDB_DATABASE=webapp
    ports:
      - "27017:27017"
    volumes:
      - db-volume:/data/db
  
  mongo-express:
    image: mongo-express:1.0.2
    container_name: webapp-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"


  api:
    image: todo-backend:latest
    container_name: webapp-go
    environment:
      # # Variables de connexion Mongo si changées.
      # - DB_ADDRESS=mongo
      # - DB_PORT=27017
      # - DB_USERNAME=root
      # - DB_PASSWORD=example

      # # Pour le ColorService (équivalent BACKGROUND_COLOR)
      - BACKGROUND_COLOR=#FFCC00
    depends_on:
      - mongo
    ports:
      - "81:81"

  front:
    image: todo-frontend:latest
    container_name: webapp-angular
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  db-volume:
